### What is NumPy?
NumPy, short for "Numerical Python," is a fundamental library for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a vast collection of mathematical functions to operate on these arrays efficiently.

Key features of NumPy include:

Multi-dimensional arrays: NumPy introduces the ndarray (n-dimensional array) object, which allows you to store and manipulate large arrays of homogeneous data types efficiently.

Broadcasting: NumPy enables arrays with different shapes to work together in arithmetic operations, making it easier to perform complex computations.

Vectorized operations: NumPy provides a wide range of mathematical functions that operate on entire arrays, eliminating the need for explicit loops and resulting in faster execution.

Integration with other libraries: NumPy serves as the foundation for many other Python libraries in the data science ecosystem, such as Pandas, Matplotlib, and Scikit-learn.

### What is Pandas?
Pandas is a powerful, open-source Python library designed for data manipulation and analysis. It provides high-performance, easy-to-use data structures and data analysis tools that make working with structured data a breeze.

Key features of Pandas include:

Data structures: Pandas introduces two primary data structures: Series (one-dimensional) and DataFrame (two-dimensional), which allow you to store and manipulate labeled and heterogeneous data efficiently.

Data manipulation: Pandas provides a wide range of functions and methods for data manipulation, such as filtering, sorting, grouping, merging, and reshaping data.

Handling missing data: Pandas offers various techniques for handling missing data, such as filling, dropping, or interpolating missing values.

Time series functionality: Pandas has extensive support for working with time series data, including date range generation, frequency conversion, and rolling window operations.

Integration with other libraries: Pandas seamlessly integrates with other Python libraries in the data science ecosystem, such as NumPy, Matplotlib, and Scikit-learn.

While NumPy and Pandas are closely related, they serve different purposes and have some key differences:

Data structures:

NumPy provides the ndarray for storing homogeneous data in multi-dimensional arrays.
Pandas introduces Series for one-dimensional labeled data and DataFrame for two-dimensional labeled data, which can hold heterogeneous data types.
Labeled data:

NumPy arrays do not have built-in support for labeled axes.
Pandas Series and DataFrame have labeled axes (index and columns), making it easier to work with structured and labeled data.
Functionality:

NumPy focuses on numerical computing and provides a wide range of mathematical functions for array operations.
Pandas builds on top of NumPy and offers additional functionality for data manipulation, cleaning, and analysis, such as handling missing data, merging datasets, and time series operations.
Use cases:

NumPy is primarily used for numerical computing, scientific computing, and performing mathematical operations on arrays.
Pandas is mainly used for data manipulation, data analysis, and data preprocessing tasks in data science and machine learning workflows.
Despite these differences, NumPy and Pandas share some similarities:

Performance: Both libraries are designed for high-performance operations on large datasets, leveraging the efficiency of C extensions under the hood.

Interoperability: Pandas is built on top of NumPy, and they can be used together seamlessly. NumPy arrays can be easily converted to Pandas Series or DataFrame, and vice versa.

Python ecosystem: Both NumPy and Pandas are essential components of the Python data science ecosystem and are widely used in conjunction with other libraries like Matplotlib and Scikit-learn.

Some key features of NumPy include:

Efficient memory usage: NumPy arrays are stored in contiguous memory blocks, allowing for faster access and computation compared to traditional Python lists.
Vectorized operations: NumPy provides a wide range of mathematical functions that operate on entire arrays, eliminating the need for explicit loops and resulting in concise and efficient code.
Broadcasting: NumPy allows arrays with different shapes to be used in arithmetic operations, enabling efficient and intuitive computations.

Over the years, NumPy has become an integral part of the scientific Python ecosystem. It serves as the foundation for many other popular libraries, such as:

SciPy: A library for scientific computing that builds upon NumPy, providing additional functionality for optimization, signal processing, and more.
Pandas: A data manipulation library that uses NumPy arrays as its underlying data structure.
Matplotlib: A plotting library that relies on NumPy for numerical computations and data representation.

In [3]:
import numpy as np
np.__version__

'2.3.3'

Here are some key characteristics of NumPy arrays:

Homogeneous: All elements in a NumPy array must be of the same data type.
Multidimensional: NumPy arrays can have one or more dimensions, allowing you to represent vectors, matrices, and higher-dimensional tensors.
Fixed Size: The size of a NumPy array is fixed at creation time and cannot be changed afterward.

NumPy arrays are represented by the ndarray object in NumPy. The dimensions of an array are called axes, and the number of axes is referred to as the rank of the array.

For example, a 1-dimensional array (rank 1) is a vector, a 2-dimensional array (rank 2) is a matrix, and arrays with rank 3 or higher are called higher-dimensional arrays or tensors.

<div style="text-align: center">
<img src="../image/scalar-vector-matrix-tensor.png" alt="From Pytopia GitHub - Dimension and Rank for Arrays in Numpy" width="400"/>
</div>

NumPy arrays offer several advantages over traditional Python lists:

Efficiency: NumPy arrays are stored in contiguous memory locations, allowing for faster access and manipulation compared to Python lists. This is especially beneficial when working with large datasets.

Vectorized Operations: NumPy provides a wide range of mathematical functions that operate element-wise on arrays, eliminating the need for explicit loops. This vectorization leads to more concise and efficient code.

Broadcasting: NumPy arrays support broadcasting, which allows arrays with different shapes to be used in arithmetic operations without the need for explicit reshaping. Broadcasting enables you to write more expressive and readable code.

Memory Efficiency: NumPy arrays are more memory-efficient than Python lists, especially for large datasets. NumPy uses fixed-size data types, which reduces memory overhead and allows for optimized memory allocation.

Interoperability: NumPy arrays seamlessly integrate with other scientific computing libraries in Python, such as SciPy, Pandas, and Matplotlib. This interoperability enables you to leverage the full power of the scientific Python ecosystem.


In [ ]:
# Create numpy array
# Creating 1-Dimentional Arrays - Using various iterables in Python

import numpy as np
arr0 = np.array([1, 2, 3, 4, 5,6]) # from list
arr0

arr1 = np.array((1, 2, 3, 4, 5,6)) # from tuple
arr1

arr2 = np.array(range(1,6,1)) # from tuple
arr2

array([1, 2, 3, 4, 5])

In [6]:
# np.arange() equivalent to range() in Python yet flexible to use float numbers 
arr3 = np.arange(1,30, 1.5)
arr3

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. , 11.5, 13. , 14.5, 16. ,
       17.5, 19. , 20.5, 22. , 23.5, 25. , 26.5, 28. , 29.5])

In [ ]:
# np.linespace(start value of interval, stop value of interval inclusive, num of values to generate with 50 as default, endpoint which by default is True)

arr4 = np.linspace(10, 40)
arr4

array([10.        , 10.6122449 , 11.2244898 , 11.83673469, 12.44897959,
       13.06122449, 13.67346939, 14.28571429, 14.89795918, 15.51020408,
       16.12244898, 16.73469388, 17.34693878, 17.95918367, 18.57142857,
       19.18367347, 19.79591837, 20.40816327, 21.02040816, 21.63265306,
       22.24489796, 22.85714286, 23.46938776, 24.08163265, 24.69387755,
       25.30612245, 25.91836735, 26.53061224, 27.14285714, 27.75510204,
       28.36734694, 28.97959184, 29.59183673, 30.20408163, 30.81632653,
       31.42857143, 32.04081633, 32.65306122, 33.26530612, 33.87755102,
       34.48979592, 35.10204082, 35.71428571, 36.32653061, 36.93877551,
       37.55102041, 38.16326531, 38.7755102 , 39.3877551 , 40.        ])

In [8]:
arr5 = np.linspace(10, 40, 20)
arr5

array([10.        , 11.57894737, 13.15789474, 14.73684211, 16.31578947,
       17.89473684, 19.47368421, 21.05263158, 22.63157895, 24.21052632,
       25.78947368, 27.36842105, 28.94736842, 30.52631579, 32.10526316,
       33.68421053, 35.26315789, 36.84210526, 38.42105263, 40.        ])

In [11]:
arr6 = np.linspace(10, 40, 10, False) # Do not include the stop!
arr6

array([10., 13., 16., 19., 22., 25., 28., 31., 34., 37.])

In [ ]:
# Creating 2-Dimensional Arrays (Matrices)
arr7 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr7
arr7[1,2]



np.int64(6)

In [16]:
# Using np.zeros() to create 2-d array filled with zeros! THe tuple/list inside (number of rows, number of columns)
arr8 = np.zeros([2,3])
arr8
arr9 = np.zeros((3, 4))
arr9

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
# using np.ones()

arr10 = np.ones((3,5))
arr10

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# np.eye() to create a 2-D indentity matrix (main diagonal is one and therest are Zeros!) - Must be SQUARE so one number if enough

arr11 = np.eye(8,8)
arr11
arr12 = np.eye(5)
arr12

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
# arr13 = np.diag() create 2-D diagonal matrix - Non-zero elements only on the main diagonal, and takes one-D array or a list as input

arr13 = np.diag([3,4,5,6,7,10])
arr13

array([[ 3,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0],
       [ 0,  0,  5,  0,  0,  0],
       [ 0,  0,  0,  6,  0,  0],
       [ 0,  0,  0,  0,  7,  0],
       [ 0,  0,  0,  0,  0, 10]])

In [25]:
# nD Array - Tensors
arrt0 = np.array([[[1,2], [3,4], [5,6]], [[7,8], [9,10],[11,12]], [[13,14],[15,16],[17,18]]])
arrt0

# We are creating 3 matrices, each have 3 rows and 2 columns (3,3,2) - To see the shape (dimensions)
arrt0.shape


(3, 3, 2)

In [26]:
arrt1 = np.zeros((4,2,5))
arrt1

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [27]:
arrt2 = np.ones((4, 2,5))
arrt2

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
# More than 3 Dimensions - Check the number of brakets
arrt3 = np.array([
    [[[1, 2], [3, 4]], [[5, 6], [7, 8]]],
    [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]
])
arrt3 # Two blocks, each contain 2 matrices that has 2 rows and 2 columns

arrt3.shape

(2, 2, 2, 2)

In [32]:
arrt4 = np.zeros((3, 4, 3,5))
arrt4

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0

In [33]:
arrt5 = np.ones((4, 3, 3,4))
arrt5

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]

In [34]:
# To see the data tupe - arr.dtype

np.array([2, 5, 7, 8]).dtype

np.array(["ali", "hassan", "hossein"]).dtype

dtype('<U7')

In [35]:
np.array([2.2, 5.5, 7.8, 8.12]).dtype

dtype('float64')

In [36]:
my_arr = np.array([2, 5, 7 ,8], dtype=np.float64)
my_arr

array([2., 5., 7., 8.])


Common NumPy Data Types
NumPy provides a wide range of data types to suit different numerical requirements. Here are some commonly used NumPy data types:

Integer Types:

np.int8: 8-bit signed integer
np.int16: 16-bit signed integer
np.int32: 32-bit signed integer (default integer type)
np.int64: 64-bit signed integer
np.uint8: 8-bit unsigned integer
np.uint16: 16-bit unsigned integer
np.uint32: 32-bit unsigned integer
np.uint64: 64-bit unsigned integer
Floating-Point Types:

np.float16: 16-bit half-precision floating-point
np.float32: 32-bit single-precision floating-point
np.float64: 64-bit double-precision floating-point (default float type)
Complex Types:

np.complex64: Complex number represented by two 32-bit floats
np.complex128: Complex number represented by two 64-bit floats
Boolean Type:

np.bool: Boolean (True or False)
String Type:

np.str: String (fixed-length)
Object Type:

np.object: Python object
When creating arrays, if you don't specify the dtype parameter, NumPy will infer the data type based on the input data. However, it's good practice to explicitly specify the data type when you have specific requirements or when you want to ensure consistent behavior across different platforms.

In [37]:
# Random NUmber Generating
# The np.random.rand() function generates an array of random numbers uniformly distributed between 0 and 1 (exclusive). You can specify the shape of the array as arguments to the function.

arrand0 = np.random.random(10)

arrand0

array([0.36924015, 0.61859129, 0.98858654, 0.65650603, 0.24574872,
       0.10036479, 0.76893618, 0.87396358, 0.18327967, 0.03276587])

In [38]:
arrand1 = np.random.rand(2,3,4) # 2 container with two matrix of 3 rows and 4 columns 
arrand1

array([[[0.35049708, 0.40017932, 0.29296896, 0.19249129],
        [0.69575575, 0.08154046, 0.08315761, 0.0099896 ],
        [0.80747606, 0.56199767, 0.95566372, 0.78410407]],

       [[0.97209423, 0.15382216, 0.25250389, 0.82005074],
        [0.39342485, 0.89977645, 0.55029551, 0.76885331],
        [0.03706422, 0.18187076, 0.28648809, 0.81932571]]])

In [39]:
arrand2 = np.random.rand(3,4) # matrix of 3 rows and 4 columns 
arrand2

array([[0.35784636, 0.7808763 , 0.93183109, 0.68378367],
       [0.20684325, 0.91264596, 0.6503696 , 0.16942818],
       [0.71453807, 0.69050288, 0.75338713, 0.41788351]])

In [41]:
# The np.random.randn() function generates an array of random numbers from the standard normal distribution (mean = 0, variance = 1). Similar to np.random.rand(), you can specify the shape of the array as arguments to the function.

arrand3 = np.random.randn(2,3,6) # Create STD normal distribution (mean of = ZERO and Variance = 1)
arrand3

array([[[-0.10844484,  0.49144747, -1.16797756, -0.72813071,
          0.28242127,  0.26469591],
        [ 0.93047278,  0.07218503, -1.28921101, -1.44600511,
          0.97302299,  0.25398034],
        [-0.67803446,  0.33030851,  1.47095992, -0.52747128,
         -0.47031022,  0.28595902]],

       [[-1.12135124,  1.27913517,  0.64581597,  0.55671454,
         -1.73116276,  1.03269621],
        [ 0.75858518, -1.39347783,  0.93137542, -0.65373263,
          0.98880201,  1.99263788],
        [ 0.61069263,  0.42795112, -0.51924434,  1.69097501,
         -0.10687682, -0.56678422]]])

In [ ]:
#The np.random.randint() function generates an array of random integers within a specified range. You can specify the lower and upper bounds of the range (inclusive) and the shape of the array.

arrand4 = np.random.randint(2,3,size=6)
arrand4

array([2, 2, 2, 2, 2, 2])

In [43]:
arrand5 = np.random.randint(low=2,high=70,size=(2, 4 ,5))
arrand5

array([[[21, 30, 42, 65, 30],
        [28, 40, 31, 16, 54],
        [28, 26, 21, 10, 23],
        [38, 57, 48, 52, 28]],

       [[ 4, 24, 58, 58, 37],
        [31, 15,  5, 32, 12],
        [25, 40, 29, 57, 29],
        [40,  7, 47, 63, 58]]])